version: '3.1'

services:

  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lucasgiovanini
      MYSQL_DATABASE: DBturismo

  api:
    image: python
    restart: always
    ports:
      - "5000:5000"
    command: flask run
    depends_on:
      - db

